name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  get_it: ^7.6.0
  injectable: ^2.1.2
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
  entities:
    path: ../entities
  server:
    path: ../server
  repository:
    path: ../repository

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  freezed: ^2.3.5