name: entities
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  freezed: ^2.3.5
  build_runner: ^2.4.6
