name: repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  rx_shared_preferences: ^3.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
